apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kubernetesclusterlast-fc06"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kubernetesclusterlast-fc06"
  template:
    metadata:
      labels:
        app: "kubernetesclusterlast-fc06"
    spec:
      containers:
        - name: "kubernetesclusterlast-fc06"
          image: "containerlastattempt.azurecr.io/kubernetesclusterlast"
          ports:
          - containerPort: 80