apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kubeclustersecondlast-fc85"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kubeclustersecondlast-fc85"
  template:
    metadata:
      labels:
        app: "kubeclustersecondlast-fc85"
    spec:
      containers:
        - name: "kubeclustersecondlast-fc85"
          image: "container5000.azurecr.io/kubeclustersecondlast"
          ports:
          - containerPort: 5000