apiVersion: v1
kind: Service
metadata:
    name: "kubernetesfourth-f39b"
    labels:
        app: "kubernetesfourth-f39b"
spec:
    type: ClusterIP
    ports:
    - port: 5001
      targetPort: 5001
      protocol: TCP
      name: http
    selector:
        app: "kubernetesfourth-f39b"