apiVersion: v1
kind: Service
metadata:
    name: "kubeclustersecondlast-882d"
    labels:
        app: "kubeclustersecondlast-882d"
spec:
    type: ClusterIP
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "kubeclustersecondlast-882d"