apiVersion: v1
kind: Service
metadata:
    name: "grpckube-4a29"
    labels:
        app: "grpckube-4a29"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "grpckube-4a29"