apiVersion: v1
kind: Service
metadata:
    name: "kubeclustersecondlast-fc85"
    labels:
        app: "kubeclustersecondlast-fc85"
spec:
    type: ClusterIP
    ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
    selector:
        app: "kubeclustersecondlast-fc85"