apiVersion: v1
kind: Service
metadata:
    name: "kubeclusterfifth-d6b7"
    labels:
        app: "kubeclusterfifth-d6b7"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "kubeclusterfifth-d6b7"