using System;
using System.Collections.Generic;

#nullable disable

namespace Demo_Project.Repository.Database
{
    public partial class Employee
    {
        public int Empnum { get; set; }
        public string EmpnumDistrict { get; set; }
        public string Lastname { get; set; }
        public string Firstname { get; set; }
        public DateTime Hiredate { get; set; }
        public string Vehicle { get; set; }
        public string Emptype { get; set; }
        public string Socsec { get; set; }
        public DateTime? Birthday { get; set; }
        public string Phone { get; set; }
        public string Addr1 { get; set; }
        public string Addr2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Certnum { get; set; }
        public DateTime? Certdate { get; set; }
        public string Licnum { get; set; }
        public DateTime? Licexpdate { get; set; }
        public short? Seniority { get; set; }
        public string User1 { get; set; }
        public string User2 { get; set; }
        public string User3 { get; set; }
        public string User4 { get; set; }
        public string User5 { get; set; }
        public DateTime? Userdate1 { get; set; }
        public DateTime? Userdate2 { get; set; }
        public float? Monhrs { get; set; }
        public float? Tuehrs { get; set; }
        public float? Wedhrs { get; set; }
        public float? Thuhrs { get; set; }
        public float? Frihrs { get; set; }
        public float? Sathrs { get; set; }
        public float? Sunhrs { get; set; }
        public float? Tothrs { get; set; }
        public float? Schedhrs { get; set; }
        public double? Ptothrs { get; set; }
        public float? Pschedhrs { get; set; }
        public float? Basehrs { get; set; }
        public float? AssignhrsAct { get; set; }
        public float? AssignhrsEst { get; set; }
        public float? RefusedhrsAct { get; set; }
        public float? RefusedhrsEst { get; set; }
        public float? Totpayhrs { get; set; }
        public float Billhrlyrate { get; set; }
        public float? Billwaithrlyrate { get; set; }
        public float Billotrate { get; set; }
        public float? Billdailyotrate { get; set; }
        public float? Billotwaitrate { get; set; }
        public int? Billdailyotwaitrate { get; set; }
        public float? Billhrlyrate2 { get; set; }
        public float? Billwaithrlyrate2 { get; set; }
        public float? Billotrate2 { get; set; }
        public float? Billdailyotrate2 { get; set; }
        public float? Billotwaitrate2 { get; set; }
        public int? Billdailyotwaitrate2 { get; set; }
        public float? Billhrlyrate3 { get; set; }
        public float? Billwaithrlyrate3 { get; set; }
        public float? Billotrate3 { get; set; }
        public float? Billdailyotrate3 { get; set; }
        public float? Billotwaitrate3 { get; set; }
        public int? Billdailyotwaitrate3 { get; set; }
        public float? Billhrlyrate4 { get; set; }
        public float? Billwaithrlyrate4 { get; set; }
        public float? Billotrate4 { get; set; }
        public float? Billdailyotrate4 { get; set; }
        public float? Billotwaitrate4 { get; set; }
        public int? Billdailyotwaitrate4 { get; set; }
        public float? Billhrlyrate5 { get; set; }
        public float? Billwaithrlyrate5 { get; set; }
        public float? Billotrate5 { get; set; }
        public float? Billdailyotrate5 { get; set; }
        public float? Billotwaitrate5 { get; set; }
        public int? Billdailyotwaitrate5 { get; set; }
        public float? Billhrlyrate6 { get; set; }
        public float? Billwaithrlyrate6 { get; set; }
        public float? Billotrate6 { get; set; }
        public float? Billdailyotrate6 { get; set; }
        public float? Billotwaitrate6 { get; set; }
        public int? Billdailyotwaitrate6 { get; set; }
        public int? Bidallowance { get; set; }
        public string Email { get; set; }
        public bool? Active { get; set; }
        public DateTime? Inactdate { get; set; }
        public string Middlename { get; set; }
        public byte[] Photo { get; set; }
        public string Ethnicity { get; set; }
        public string Gender { get; set; }
        public string Birthplace { get; set; }
        public string Additphone { get; set; }
        public string Additphonedesc { get; set; }
        public string Mailaddr1 { get; set; }
        public string Mailaddr2 { get; set; }
        public string Mailcity { get; set; }
        public string Mailstate { get; set; }
        public string Mailzip { get; set; }
        public string Licstate { get; set; }
        public string Licclass { get; set; }
        public string Licendorsement { get; set; }
        public int? Supervisor { get; set; }
        public string Empstatus { get; set; }
        public DateTime? Empstatusdate { get; set; }
        public string Division { get; set; }
        public string Department { get; set; }
        public string Pin { get; set; }
        public string CheckInMessage { get; set; }
        public DateTime? MessageBeginDate { get; set; }
        public DateTime? MessageEndDate { get; set; }
        public DateTime? MessageBeginTime { get; set; }
        public DateTime? MessageEndTime { get; set; }
        public string User6 { get; set; }
        public string User7 { get; set; }
        public string User8 { get; set; }
        public string User9 { get; set; }
        public string User10 { get; set; }
        public DateTime? Userdate3 { get; set; }
        public DateTime? Userdate4 { get; set; }
        public DateTime? Userdate5 { get; set; }
        public string Zonarid { get; set; }
        public byte[] SsmaTimeStamp { get; set; }
    }
}
