on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: containeradmin.azurecr.io
        username: ${{ secrets.acr_containeradmin_username }}
        password: ${{ secrets.acr_containeradmin_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/Demo-Project" -f  "Demo-Project/Dockerfile" -t containeradmin.azurecr.io/kubeclustersecondlast:${{ github.sha }} --label dockerfile-path=Demo-Project/Dockerfile
        docker push containeradmin.azurecr.io/kubeclustersecondlast:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kubeclustersecondlast_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kubecluster-secondlast8bd4 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kubecluster-secondlast8bd4`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kubecluster-secondlast8bd4
        container-registry-url: containeradmin.azurecr.io
        container-registry-username: ${{ secrets.acr_containeradmin_username }}
        container-registry-password: ${{ secrets.acr_containeradmin_password }}
        secret-name: kubeclustersdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: kubecluster-secondlast8bd4
        manifests: |
          manifests/deployment-12.yml
          manifests/service-12.yml
          manifests/ingress-10.yml
        images: |
          containeradmin.azurecr.io/kubeclustersecondlast:${{ github.sha }}
        imagepullsecrets: |
          kubeclustersdockerauth
